# Node.js with Angular
# Build a Node.js project that uses Angular.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/javascript

trigger:
- master

pool:
  vmImage: ubuntu-latest

steps:
- task: NodeTool@0
  inputs:
    versionSource: 'spec'
    versionSpec: '14.20.1'
  displayName: 'Install Node.js'

- script: |
    npm install -g @angular/cli@1.0.0
    npm install
    ng build --prod --aot=false
  displayName: 'npm install and build'
  
# - task: ArchiveFiles@2
#   displayName: 'Archive files'
#   inputs:
#     rootFolderOrFile: '$(System.DefaultWorkingDirectory)'
#     includeRootFolder: false
#     archiveType: zip
#     archiveFile: $(Build.ArtifactStagingDirectory)/$(Build.BuildId).zip
#     replaceExistingArchive: true

# - upload: $(Build.ArtifactStagingDirectory)/$(Build.BuildId).zip
#   artifact: drop


# - task: CopyFiles@2
#   inputs:
#     SourceFolder: '$(Build.SourcesDirectory)'
#     Contents: |
#        src/*
#        public/*
#     TargetFolder: '$(Build.ArtifactStagingDirectory)'
#     OverWrite: true
#   displayName: 'Copy project files'

- task: CopyFiles@2
  inputs:
    sourceFolder: '$(Build.SourcesDirectory)'
    contents: |
       src/*
       public/*
    targetFolder: '$(Build.ArtifactStagingDirectory)'
  displayName: 'Copy project files'

- task: PublishPipelineArtifact@1
  inputs:
    artifactName: e2e-server
    targetPath: '$(Build.ArtifactStagingDirectory)'
    publishLocation: 'pipeline'
  displayName: 'Publish npm artifact'
- task: PublishPipelineArtifact@1
  inputs:
    artifactName: CiscoEmulator
    targetPath: '$(Build.ArtifactStagingDirectory)'
    publishLocation: 'pipeline'
  displayName: 'Publish npm artifact'

# - task: AzureRmWebAppDeployment@4
#   inputs:
#     ConnectionType: 'AzureRM'
#     azureSubscription: 'BlueVisionAzure'
#     appType: 'webApp'
#     WebAppName: 'ciscoemulator'
#     packageForLinux: '$(System.DefaultWorkingDirectory)/**/*.zip'