# Node.js with Angular
# Build a Node.js project that uses Angular.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/javascript

trigger:
- master

variables:

  # Azure Resource Manager connection created during pipeline creation
  azureSubscription: 'BlueVisionAzure'
  
  # Web app name
  webAppName: 'CiscoEmulator'
  
  # Environment name
  environmentName: 'Production'

  # Agent VM image name
  vmImageName: 'ubuntu-latest'

pool:
  vmImage: $(vmImageName)

stages:
- stage: Build
  displayName: Build stage
  jobs:  
  - job: Build
    displayName: Build
    pool:
      vmImage: $(vmImageName)

    steps:
    - task: NodeTool@0
      displayName: 'Install Node.js'
      retryCountOnTaskFailure: 3
      inputs:
        versionSource: 'spec'
        versionSpec: '14.18.3'

    - script: |
        npm install -g @angular/cli@1.0.0
        npm install
        ng build
      displayName: 'Install Node Packages and Build the App'
      
    - script: |
        ng test
      displayName: 'Run Tests'
      condition: 
    
    - script: |
        ng lint
      displayName: 'Run Linter'
  
    - task: ArchiveFiles@2
      displayName: 'Archive files in the DIST folder'
      inputs:
        rootFolderOrFile: '$(System.DefaultWorkingDirectory)/dist'
        includeRootFolder: false
        archiveType: zip
        archiveFile: $(Build.ArtifactStagingDirectory)/$(Build.BuildId).zip
        replaceExistingArchive: true

    - upload: $(Build.ArtifactStagingDirectory)/$(Build.BuildId).zip
      artifact: drop


- stage: Deploy
  displayName: Deploy stage
  dependsOn: Build
  condition: succeeded()
  jobs:
  - deployment: Deploy
    displayName: Deploy
    environment: $(environmentName)
    pool: 
      vmImage: $(vmImageName)
    strategy:
      runOnce:
        deploy:
          steps:
          - task: AzureRmWebAppDeployment@4
            displayName: 'Deploy the CiscoEmulator Azure Web App Deploy'
            inputs:
              ConnectionType: 'AzureRM'
              azureSubscription: '$(azureSubscription)'
              appType: 'webApp'
              WebAppName: 'ciscoemulator'
              packageForLinux: '$(Pipeline.Workspace)/drop/$(Build.BuildId).zip'