import { TerminalCommand } from '../../interfaces/terminal-command';
import {NotSupportedCommand} from './notsupported';

export let unsupportedConfInterfaceCommands: TerminalCommand[] = [
{ name: 'aaa', description: 'Authentication, Authorization and Accounting',
     handler: NotSupportedCommand.NotSupported },
{ name: 'access-expression', description: 'Build a bridge boolean access expression',
     handler: NotSupportedCommand.NotSupported },
{ name: 'access-session', description: 'Access Session specific Interface Configuration Commands',
     handler: NotSupportedCommand.NotSupported },
{ name: 'apollo', description: 'Apollo interface subcommands',
     handler: NotSupportedCommand.NotSupported },
{ name: 'arp', description: 'Set arp type (arpa, probe, snap) or timeout or log options',
     handler: NotSupportedCommand.NotSupported },
{ name: 'authentication', description: 'Auth Manager Interface Configuration Commands',
     handler: NotSupportedCommand.NotSupported },
{ name: 'backup', description: 'Modify backup parameters',
     handler: NotSupportedCommand.NotSupported },
{ name: 'bandwidth', description: 'Set bandwidth informational parameter',
     handler: NotSupportedCommand.NotSupported },
{ name: 'bfd', description: 'BFD interface configuration commands',
     handler: NotSupportedCommand.NotSupported },
{ name: 'bgpPolicy', description: 'Apply policy propagated by bgp community string',
     handler: NotSupportedCommand.NotSupported },
{ name: 'carrier-delay', description: 'Specify delay for interface transitions',
     handler: NotSupportedCommand.NotSupported },
{ name: 'cdp', description: 'CDP interface subcommands',
     handler: NotSupportedCommand.NotSupported },
{ name: 'cmns', description: 'OSI CMNS',
     handler: NotSupportedCommand.NotSupported },
{ name: 'crypto', description: 'Encryption/Decryption commands',
     handler: NotSupportedCommand.NotSupported },
{ name: 'custom-queue-list', description: 'Assign a custom queue list to an interface',
     handler: NotSupportedCommand.NotSupported },
{ name: 'dampening', description: 'Enable event dampening',
     handler: NotSupportedCommand.NotSupported },
{ name: 'decnet', description: 'Interface DECnet config commands',
     handler: NotSupportedCommand.NotSupported },
{ name: 'default', description: 'Set a command to its defaults',
     handler: NotSupportedCommand.NotSupported },
{ name: 'delay', description: 'Specify interface throughput delay',
     handler: NotSupportedCommand.NotSupported },
{ name: 'description', description: 'Interface specific description',
     handler: NotSupportedCommand.NotSupported },
{ name: 'dlsw', description: 'DLSw interface subcommands', handler: NotSupportedCommand.NotSupported },
{ name: 'dot1q', description: 'dot1q interface configuration commands', handler: NotSupportedCommand.NotSupported },
{ name: 'dot1x', description: 'Interface Config Commands for IEEE 802.1X', handler: NotSupportedCommand.NotSupported },
{ name: 'dspu', description: 'Down Stream PU', handler: NotSupportedCommand.NotSupported },
{ name: 'duplex', description: 'Configure duplex operation', handler: NotSupportedCommand.NotSupported },
{ name: 'ethernet', description: 'Ethernet interface parameters', handler: NotSupportedCommand.NotSupported },
{ name: 'fair-queue', description: 'Enable Fair Queuing on an Interface', handler: NotSupportedCommand.NotSupported },
{ name: 'flow-sampler', description: 'Attach flow sampler to the interface', handler: NotSupportedCommand.NotSupported },
{ name: 'flowcontrol', description: 'Configure flow operation', handler: NotSupportedCommand.NotSupported },
{ name: 'fras', description: 'DLC Switch Interface Command', handler: NotSupportedCommand.NotSupported },
{ name: 'help', description: 'Description of the interactive help system', handler: NotSupportedCommand.NotSupported },
{ name: 'history', description: 'Interface history histograms - 60 second, 60 minute and hour',
     handler: NotSupportedCommand.NotSupported },
{ name: 'hold-queue', description: 'Set hold queue depth', handler: NotSupportedCommand.NotSupported },
{ name: 'ipv6', description: 'IPv6 interface subcommands', handler: NotSupportedCommand.NotSupported },
{ name: 'isis', description: 'IS-IS commands', handler: NotSupportedCommand.NotSupported },
{ name: 'iso-igrp', description: 'ISO-IGRP interface subcommands', handler: NotSupportedCommand.NotSupported },
{ name: 'l2protocol', description: 'Configure l2 control protocol processing',
     handler: NotSupportedCommand.NotSupported },
{ name: 'l2protocol-tunnel', description: 'Tunnel Layer2 protocols', handler: NotSupportedCommand.NotSupported },
{ name: 'lacp', description: 'LACP interface subcommands', handler: NotSupportedCommand.NotSupported },
{ name: 'lanName', description: 'LAN Name command', handler: NotSupportedCommand.NotSupported },
{ name: 'lat', description: 'LAT commands', handler: NotSupportedCommand.NotSupported },
{ name: 'link', description: 'Interface link related commands', handler: NotSupportedCommand.NotSupported },
{ name: 'llc2', description: 'LLC2 Interface Subcommands', handler: NotSupportedCommand.NotSupported },
{ name: 'lldp', description: 'LLDP interface subcommands', handler: NotSupportedCommand.NotSupported },
{ name: 'load-interval', description: 'Specify interval for load calculation for an interface',
     handler: NotSupportedCommand.NotSupported },
{ name: 'locaddr-priority', description: 'Assign a priority group', handler: NotSupportedCommand.NotSupported },
{ name: 'location', description: 'Interface location information', handler: NotSupportedCommand.NotSupported },
{ name: 'logging', description: 'Configure logging for interface', handler: NotSupportedCommand.NotSupported },
{ name: 'loopback', description: 'Configure internal loopback on an interface',
     handler: NotSupportedCommand.NotSupported },
{ name: 'mab', description: 'MAC Authentication Bypass Interface Config Commands',
     handler: NotSupportedCommand.NotSupported },
{ name: 'mac', description: 'MAC interface commands', handler: NotSupportedCommand.NotSupported },
{ name: 'mac-address', description: 'Manually set interface MAC address',
     handler: NotSupportedCommand.NotSupported },
{ name: 'macro', description: 'Command macro', handler: NotSupportedCommand.NotSupported },
{ name: 'media-type', description: 'Configure media type', handler: NotSupportedCommand.NotSupported },
{ name: 'metadata', description: 'Metadata Application', handler: NotSupportedCommand.NotSupported },
{ name: 'mpls', description: 'Configure MPLS interface parameters', handler: NotSupportedCommand.NotSupported },
{ name: 'mtu', description: 'Set the interface Maximum Transmission Unit (MTU',
     handler: NotSupportedCommand.NotSupported },
{ name: 'negotiation', description: 'Select autonegotiation mode', handler: NotSupportedCommand.NotSupported },
{ name: 'netbios', description: 'Use a defined NETBIOS access list or enable name-caching',
     handler: NotSupportedCommand.NotSupported },
{ name: 'nmsp', description: 'NMSP interface configuration', handler: NotSupportedCommand.NotSupported },
{ name: 'onep', description: 'Configure onep settings', handler: NotSupportedCommand.NotSupported },
{ name: 'pagp', description: 'PAgP interface subcommands', handler: NotSupportedCommand.NotSupported },
{ name: 'priority-group', description: 'Assign a priority group to an interface',
     handler: NotSupportedCommand.NotSupported },
{ name: 'random-detect', description: 'Enable Weighted Random Early Detection (WRED) on an Interface',
     handler: NotSupportedCommand.NotSupported },
{ name: 'rate-limit', description: 'Rate Limit', handler: NotSupportedCommand.NotSupported },
{ name: 'routing', description: 'Per-interface routing configuration', handler: NotSupportedCommand.NotSupported },
{ name: 'sap-priority', description: 'Assign a priority group', handler: NotSupportedCommand.NotSupported },
{ name: 'service', description: 'Configure Ether Service', handler: NotSupportedCommand.NotSupported },
{ name: 'service-policy', description: 'Configure CPL Service Policy', handler: NotSupportedCommand.NotSupported },
{ name: 'smrp', description: 'Simple Multicast Routing Protocol interface subcommands',
     handler: NotSupportedCommand.NotSupported },
{ name: 'sna', description: 'SNA pu configuration', handler: NotSupportedCommand.NotSupported },
{ name: 'snapshot', description: 'Configure snapshot support on the interface',
     handler: NotSupportedCommand.NotSupported },
{ name: 'snmp', description: 'Modify SNMP interface parameters', handler: NotSupportedCommand.NotSupported },
{ name: 'source', description: 'Get config from another source', handler: NotSupportedCommand.NotSupported },
{ name: 'spanning-tree', description: 'Spanning Tree Subsystem', handler: NotSupportedCommand.NotSupported },
{ name: 'speed', description: 'Configure speed operation', handler: NotSupportedCommand.NotSupported },
{ name: 'subscriber', description: 'Subscriber inactivity timeout value',
     handler: NotSupportedCommand.NotSupported },
{ name: 'tarp', description: 'TARP interface subcommands', handler: NotSupportedCommand.NotSupported },
{ name: 'timeout', description: 'Define timeout values for this interface',
     handler: NotSupportedCommand.NotSupported },
{ name: 'topology', description: 'Configure routing topology on the interface',
     handler: NotSupportedCommand.NotSupported },
{ name: 'traffic-shape', description: 'Enable Traffic Shaping on an Interface or Sub-Interface',
     handler: NotSupportedCommand.NotSupported },
{ name: 'transmit-interface', description: 'Assign a transmit interface to a receive-only interface',
     handler: NotSupportedCommand.NotSupported },
{ name: 'tx-ring-limit', description: 'Configure PA level transmit ring limit',
     handler: NotSupportedCommand.NotSupported },
{ name: 'udld', description: 'Configure UDLD enabled or disabled and ignore global UDLD setting',
     handler: NotSupportedCommand.NotSupported },
{ name: 'vines', description: 'VINES interface subcommands', handler: NotSupportedCommand.NotSupported }

];
