import { TerminalCommand } from '../../interfaces/terminal-command';
import { NotSupportedCommand } from './notsupported';

export let unsupportedDeviceCommands: TerminalCommand[] = [
    { name: 'access-enable', description: 'Create a temporary Access-List entry' },
    { name: 'access-profile', description: 'Apply user-profile to interface' },
    { name: 'clear', description: 'Reset functions' },
    { name: 'connect', description: 'Open a terminal connection' },
    { name: 'crypto', description: 'Encryption related commands.' },
    { name: 'disable', description: 'Turn off privileged commands' },
    { name: 'disconnect', description: 'Disconnect an existing network connection' },
    { name: 'do-exec', description: 'Mode-independent "do-exec" prefix support' },
    { name: 'ethernet', description: 'Ethernet parameters' },
    { name: 'help', description: 'Description of the interactive help system' },
    { name: 'lat', description: 'Open a lat connection' },
    { name: 'lock', description: 'Lock the terminal' },
    { name: 'login', description: 'Log in as a particular user' },
    { name: 'mrinfo', description: 'Request neighbor and version information from a multicast router' },
    { name: 'mstat', description: 'Show statistics after multiple multicast traceroutes' },
    { name: 'mtrace', description: 'Trace reverse multicast path from destination to source' },
    { name: 'name-connection', description: 'Name an existing network connection' },
    { name: 'pad', description: 'Open a X.29 PAD connection' },
    { name: 'ppp', description: 'Start IETF Point-to-Point Protocol (PPP)' },
    { name: 'release', description: 'Release a resource' },
    { name: 'renew', description: 'Renew a resource' },
    { name: 'resume', description: 'Resume an active network connection' },
    { name: 'rlogin', description: 'Open an rlogin connection' },
    { name: 'routing-context', description: 'Routing Context' },
    { name: 'set', description: 'Set system parameter (not config)' },
    { name: 'slip', description: 'Start Serial-line IP (SLIP)' },
    { name: 'ssh', description: 'Open a secure shell client connection' },
    { name: 'systat', description: 'Display information about terminal lines' },
    { name: 'tclquit', description: 'Quit Tool Command Language shell' },
    { name: 'telnet', description: 'Open a telnet connection' },
    { name: 'terminal', description: 'Set terminal line parameters' },
    { name: 'tn3270', description: 'Open a tn3270 connection' },
    { name: 'traceroute', description: 'Trace route to destination' },
    { name: 'tunnel', description: 'Open a tunnel connection' },
    { name: 'udptn', description: 'Open an udptn connection' },
    { name: 'where', description: 'List active connections' },
    { name: 'x28', description: 'Become an X.28 PAD' },
    { name: 'x3', description: 'Set X.3 parameters on PAD' },
    { name: 'xremote', description: 'Enter XRemote mode' },
];
